### ISSUE TITLE
Ignore order of environment variables for Marathon jobs

### ISSUE THREAD

**Issue by SHyx0rmZ** [trivago/chapi#86]
When showing diffs for Marathon jobs, chapi will show changes in the order of the environment variables, even when nothing about the configuration itself changed. As this seems to be a problem just concerning ordering in the diff and visualization, I think it would be an improvement to have chapi ignore those changes.

**Comment by andygrunwald** [comment]
Can you provide the steps to reproduce this?

Maybe a good idea would be to adjust your ticket description according to our new [ISSUE_TEMPLATE](https://github.com/trivago/chapi/blob/master/.github/ISSUE_TEMPLATE.md).
This would offer Mesos, Chronos and Marathon version as well.
