### ISSUE TITLE
Only scan JSON files

### ISSUE THREAD

**Issue by SHyx0rmZ** [trivago/chapi#87]

**Comment by msiebeneicher** [comment]
I'm not sure if that will fit for every setup. A `.json` file extension is not mandatory for job files.

**Comment by SHyx0rmZ** [comment]
That's true. As this arose when we made a backup copy of an existing job, do we maybe, upon detection of a duplicate job, want to display a message prompting the user to move any backup copies out of the job repository, if having a backup copy was what they were trying to do?

**Comment by msiebeneicher** [comment]
We can think about it to ignore common backup file extensions like `.bak`

**Comment by andygrunwald** [comment]
Isn't this already possibly by the `.chapiconfig`+ `ignore` section with a `*.bak`?

**Comment by msiebeneicher** [comment]
uh - right - that should work
