### ISSUE TITLE
Marathon: When `"servicePort": 0` is used in a Docker Container deployment, diff shows random allocated port

### ISSUE THREAD

**Issue by andygrunwald** [trivago/chapi#90]
When you deploy a docker container as a marathon job with a `"servicePort": 0` definition, a random allocated port (from Mesos) will assigned as a `servicePort`.
With the usage of marathon-lb this is fine, because your random service port will be mapped to a domain in marathon-lb.

When you launch a golang application (without a docker env) in the same way (with `"servicePort": 0`), the Expected Behavior is the case. There, everything is working.

## Expected Behavior

When your job is deployed and you hit `chapi status`, your job is not our of sync and everything is fine

```
Changes to be committed
  (use 'chapi reset <job>...' to unstage)


Changes not staged for commit
  (use 'chapi add <job>...' to update what will be committed)
  (use 'chapi checkout <job>...' to discard changes in local repository)

  Updated jobs in local repository:
```

## Current Behavior

When your job is deployed and you hit `chapi status`, your job always shows as "modified:

```
Changes to be committed
  (use 'chapi reset <job>...' to unstage)


Changes not staged for commit
  (use 'chapi add <job>...' to update what will be committed)
  (use 'chapi checkout <job>...' to discard changes in local repository)

  Updated jobs in local repository:
	modified marathon job:	/my-service/foo
```

When you hit `chapi diff`, the diff shows the random allocated service port as a difference:

```
$ chapi diff /my-service/foo

diff /my-service/foo
	...
	container:                   "protocol": "tcp",
+	container:                  "servicePort": 0,
-	container:                  "servicePort": 10021,
	container:                   "hostPort": 0,
	...
```

## Possible Solution

Exclude `container.docker.portMappings.*.servicePort` from diff.

## Steps to Reproduce (for bugs)

1. Deploy a Docker Container with `"servicePort": 0` on Marathon
2. Hit `chapi status`, you should see your newly deployed job
3. Hit `chapi diff`, you should see a diff in your servicePort with a random allocated port

## Context

The more jobs you deploy in this way, the more "out of sync" jobs appear.
When we apply an automated check on this, this would always be red / out of sync.

## Your Environment

* Chapi version: master (rev: a171472)
* PHP version: PHP 7.0.21 (cli) (built: Jul 29 2017 09:17:51) ( NTS )
* Operating System and version: macOS Sierra 10.12.6 (16G29)
* Mesos version: 1.1.0
* Marathon version: 1.4.1
* Chronos version: 2.4.0

```
{
  "id": "/my-service/foo",
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "org/container:v1.0",
      "network": "BRIDGE",
      "portMappings": [
        {
          "containerPort": 8080,
          "hostPort": 0,
          "servicePort": 0,
          "protocol": "tcp"
        }
      ]
    }
  },
  "labels": {
    "HAPROXY_GROUP": "internal",
    "HAPROXY_0_VHOST": "my-domain.mesos-stage.trivago.trv",
  },
  "cpus": 1,
  "mem": 512,
  "instances": 1
}
```

**Comment by SHyx0rmZ** [comment]
So, the way this is currently done for non-container payloads is basically the same as what you are suggesting as a possible solution. I have extended the logic to also apply to the container port mappings, which gives the wanted behavior for `chapi status`.

We should keep in mind, though, that this also means that jobs that were previously assigned to a specific port and are now changed to have a port assigned by Marathon will no longer be part of `chapi status`. As discussions haven't yielded a better solution (yet?), I would still opt for merging this.

**Comment by andygrunwald** [comment]
> We should keep in mind, though, that this also means that jobs that were previously assigned to a specific port and are now changed to have a port assigned by Marathon will no longer be part of chapi status.

Can you elaborate this a little bit more (e.g. with an example?)

**Comment by SHyx0rmZ** [comment]
Let's say you have a job that looks like this locally and remotely:

```json
  …,
  "container": {
    "type": "DOCKER",
    "docker": {
      …,
      "portMappings": [
        {
          …,
          "servicePort": 8080,
        }
      ]
    }
  }
```

You now change your local job definition so it says `"servicePort": 0`, because you want Marathon to decide where to put it.

The output of `chapi status` will be:
```
Changes to be committed
  (use 'chapi reset <job>...' to unstage)

Changes not staged for commit
  (use 'chapi add <job>...' to update what will be committed)
  (use 'chapi checkout <job>...' to discard changes in local repository)
```

It will no longer be possible to show this job as changed.

**Comment by ppar** [comment]
Effectively the status AFAICS hasn't changed in this scenario, so chapi's behavior is correct. You're giving Marathon a free hand in choosing the port, and marathon might as well choose (to keep using) port 8080. 

IIRC I actually saw marathon actually do this if you switch from a manually allocated port to "port 0", it just keeps the port you previously allocated.

I guess Marathon's API doesn't clearly distinguish between "intended state" and "result state", so you can't diff between <intended state x> vs. <indended state y> if the resulting state is the same.
